### PR TITLE
Update iOS SDK to 2.2.0

### PR DESCRIPTION
**Pull request by nsingh-branch**
## Reference
INTENG-18507 -- Update mParticle kit to new BranchSDK version

## Summary
Updated the iOS Branch SDK from 2.1.2 to 2.2.0.

## Motivation
To give access to the add developer_identity to v1/installs.

## Type Of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing Instructions

Setup and run the mParticle test app and ensure all of the versions are correct and the functionality of the kit remains the same.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by nsingh-branch** [comment]
@einsteinx2 Would you be able to take a look at this?

**Comment by nsingh-branch** [comment]
@BrandonStalnaker Would you be able to review this?

**Comment by BrandonStalnaker** [comment]
Sorry for the delay @nsingh-branch I'm adding this to our backlog now so we can test and approve.

**Comment by nsingh-branch** [comment]
> Sorry for the delay @nsingh-branch I'm adding this to our backlog now so we can test and approve.

No problem. Thank you!

**Review by BrandonStalnaker — CHANGES_REQUESTED** [review]
Pulled this into one of our sample projects to make sure everything was good end to end but noticed an issue on line 163 of MPKitBranchMetrics.m around 'delayInitToCheckForSearchAds' no longer being a method on the Branch SDK. Should that be removed or replaced?

**Comment by BrandonStalnaker** [comment]
@nsingh-branch Just one question/possible issue.

**Review by BrandonStalnaker — APPROVED** [review]
LGTM

**Comment by nsingh-branch** [comment]
Thank you for helping out with this @BrandonStalnaker! While I have you here, I have another unrelated request regarding both of the mParticle-TUNE SDKs. Next month, the TUNE SDKs, which are deprecated, will become no-op so we would like the Github repos to be archived. Thank you!

mParticle-TUNE iOS: https://github.com/mparticle-integrations/mparticle-apple-integration-tune
mParticle-TUNE Android: https://github.com/mparticle-integrations/mparticle-android-integration-tune

**Pull request merged**
